name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - senpai
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - senpai

jobs:
  check_if_front:
    if: (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed'))
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: '[ "Web.Public/**" ]'
          cancel_others: true
          
